# vim: ft=perl
#
# Autogenerated via bin/recreate-cpanfile on Wed Nov 19 18:32:23 2025

=comment

Install all dependencies with:

    cpanm --installdeps .

See https://metacpan.org/pod/CPAN::Meta::Spec#VERSION-NUMBERS for details.

=cut

requires 'App::HTTPThis'                 => 0;
requires 'App::Sqitch'                   => 1;
requires 'Browser::Open'                 => 0.04;
requires 'CHI'                           => 0.61;
requires 'Capture::Tiny'                 => 0.50;
requires 'Class::XSAccessor'             => 1.19;
requires 'Config::Any'                   => 0.33;
requires 'Const::Fast'                   => 0.014;
requires 'DBD::SQLite'                   => 1.76;
requires 'DBI'                           => 1.647;
requires 'Dancer2'                       => v2.0.1;
requires 'DateTime'                      => 1.66;
requires 'DateTime::Format::SQLite'      => 0.11;
requires 'File::Find::Rule'              => 0.35;
requires 'File::Which'                   => 1.27;
requires 'HTML::Parser'                  => 3.83;
requires 'HTML::SimpleLinkExtor'         => 1.273;
requires 'HTML::TokeParser::Simple'      => 3.16;
requires 'HTTP::Message'                 => 7.01;
requires 'HTTP::Tiny::Mech'              => 1.001002;
requires 'Imager'                        => 0;
requires 'IPC::Run'                      => 20250809.0;
requires 'IPC::System::Simple'           => 1.30;
requires 'Import::Into'                  => 1.002005;
requires 'MetaCPAN::Client'              => 2.033000;
requires 'Module::ScanDeps'              => 1.37;
requires 'Mojolicious'                   => 9.42;
requires 'Moo'                           => 2.005005;
requires 'Moose'                         => 2.4000;
requires 'MooseX::Extended'              => 0.35;
requires 'OpenAPI::Client::OpenAI'       => 0.24;
requires 'Path::Tiny'                    => 0.150;
requires 'PerlX::Maybe'                  => 1.202;
requires 'Plack'                         => 1.0051;
requires 'Set::Object'                   => 1.43;
requires 'String::Util'                  => 1.35;
requires 'Template::Plugin::CommonMark'  => 1.000;
requires 'Template::Plugin::EnvHash'     => 1.06;
requires 'Template::Plugin::JSON'        => 0.08;
requires 'Template::Timer'               => 1.00;
requires 'Template::Tiny'                => 1.16;
requires 'Template::Tiny::Strict'        => 1.18;
requires 'Template::Toolkit'             => 3.102;
requires 'Test::MockModule'              => v0.180.0;
requires 'Test::Most'                    => 0.38;
requires 'Text::Markdown'                => 1.000031;
requires 'Text::Unidecode'               => 1.30;
requires 'Try::Tiny'                     => 0.32;
requires 'Type::Tiny'                    => 2.008004;
requires 'URI'                           => 5.34;
requires 'URI::Encode'                   => v1.1.1;
requires 'URI::Find'                     => 20160806;
requires 'URI::FromHash'                 => 0.05;
requires 'URI::Nested'                   => 0.10;
requires 'URI::Router'                   => v0.1.4;
requires 'URI::db'                       => 0.23;
requires 'WWW::Mechanize::Cached'        => 1.56;
requires 'XML::RSS'                      => 1.65;
requires 'YAML::LibYAML'                 => 0.83;
requires 'aliased'                       => 0.34;
requires 'namespace::autoclean'          => 0.31;
requires 'utf8::all'                     => 0.024;

