#!/usr/bin/env perl

# The homepage "Latest" feed, generated by Ovid::Site into
# root/include/latest.tt.
#
# The interesting case is the date. articles.created is when bin/article
# inserted the row, but the date an article page displays comes from the
# `date` line in its template preamble, and the two drift. The feed has to
# agree with the page.

use Test::Most;
use lib 'lib';
use lib 't/lib';
use Less::Boilerplate;
use Test2::Plugin::UTF8;
use Cwd        qw(getcwd);
use Path::Tiny qw(path);
use Ovid::Site;
use TestHelper::Site qw(make_test_dbh);

my $cwd = getcwd();
END { chdir $cwd }

my $site = Ovid::Site->new;

sub post (%args) {
    return {
        title       => 'A Title',
        slug        => 'a-title',
        description => 'A description.',
        created     => '2026-01-02 03:04:05',
        type        => 'article',
        directory   => 'articles',
        date        => '2026-01-02',
        %args,
    };
}

subtest 'posts render in the order they are given' => sub {
    my $html = $site->_latest_posts_html(
        [   post( slug => 'newest', title => 'Newest' ),
            post( slug => 'middle', title => 'Middle' ),
            post( slug => 'oldest', title => 'Oldest' ),
        ]
    );

    my @slugs = $html =~ m{href="/articles/(\w+)"}g;
    is_deeply \@slugs, [qw/newest middle oldest/], 'order preserved from the query';
    like $html, qr{\A<ul class="latest">}, 'wrapped in ul.latest';
    like $html, qr{</ul>\n\z},             'list is closed';
};

subtest 'the query orders by created, then sort_order to break ties' => sub {
    my $dbh = make_test_dbh();

    # The three real posts that share 2025-11-21 19:56:25. created alone
    # leaves their order to SQLite; sort_order DESC settles it the same way
    # the per-type listing pages do.
    my $insert = $dbh->prepare(<<'SQL');
INSERT INTO articles (title, slug, description, article_type_id, sort_order, created)
VALUES (?, ?, 'x', 1, ?, ?)
SQL
    $insert->execute( 'Tied A', 'tied-a', 111, '2025-11-21 19:56:25' );
    $insert->execute( 'Tied B', 'tied-b', 113, '2025-11-21 19:56:25' );
    $insert->execute( 'Tied C', 'tied-c', 112, '2025-11-21 19:56:25' );

    my $rows = $dbh->selectall_arrayref( <<'SQL', { Slice => {} } );
SELECT a.slug FROM articles a
 WHERE a.available = 1 AND a.slug LIKE 'tied-%'
 ORDER BY a.created DESC, a.sort_order DESC
SQL
    is_deeply [ map { $_->{slug} } $rows->@* ], [qw/tied-b tied-c tied-a/],
      'equal timestamps fall back to sort_order DESC';
};

subtest 'the LIMIT and the date both come from _rebuild_latest_posts' => sub {
    my $dbh     = make_test_dbh();
    my $tempdir = Path::Tiny->tempdir;

    # The fixture ships three sample rows whose created defaults to
    # CURRENT_TIMESTAMP, which would sort above anything dated here.
    $dbh->do('DELETE FROM articles');

    # 12 posts, so the LIMIT has something to cut.
    my $insert = $dbh->prepare(<<'SQL');
INSERT INTO articles (title, slug, description, article_type_id, sort_order, created)
VALUES (?, ?, 'x', 2, ?, ?)
SQL
    for my $n ( 1 .. 12 ) {
        $insert->execute(
            "Post $n", "post-$n", 100 + $n,
            sprintf( '2026-01-%02d 00:00:00', $n )
        );
    }

    # post-12 is the newest by created, but its template says otherwise.
    # bin/article writes the preamble date and lets created default to
    # CURRENT_TIMESTAMP, so this gap is the normal case, not a corruption.
    $tempdir->child('root/articles')->mkpath;
    $tempdir->child('root/include')->mkpath;
    $tempdir->child('root/articles/post-12.tt2markdown')->spew_utf8(<<'END');
[%
    title = 'Post 12';
    type  = 'articles';
    slug  = 'post-12';
    date  = '2025-08-26';
%]
[% WRAPPER include/wrapper.tt blogdown=1 -%]
body
[% END %]
END

    chdir $tempdir;
    Ovid::Site->new( dbh => $dbh )->_rebuild_latest_posts;
    my $html = $tempdir->child('root/include/latest.tt')->slurp_utf8;
    chdir $cwd;

    my @slugs = $html =~ m{href="/articles/([\w-]+)"}g;
    is scalar @slugs, 10,        'LIMIT 10 applied';
    is $slugs[0],     'post-12', 'newest by created comes first';
    unlike $html, qr/post-2"/, 'the oldest posts are cut';

    like $html, qr{<time datetime="2025-08-26">26 August 2025</time>},
      'date comes from the preamble, not created';
    unlike $html, qr/2026-01-12/,
      'the created timestamp never reaches the page';

    like $html, qr{<time datetime="2026-01-11">11 January 2026</time>},
      'a post with no source file falls back to created';
};

subtest 'descriptions are escaped, titles too' => sub {
    my $html = $site->_latest_posts_html(
        [   post(
                title       => 'Tom & Jerry <blink>',
                description => 'R&B, <script>alert(1)</script> & more > less',
            ),
        ]
    );

    like $html, qr/Tom &amp; Jerry &lt;blink&gt;/, 'title escaped';
    like $html, qr/R&amp;B, &lt;script&gt;alert\(1\)&lt;\/script&gt; &amp; more &gt; less/,
      'description escaped';
    unlike $html, qr/<script>/, 'no raw script tag survives';
};

subtest '_human_date formats and refuses to guess' => sub {
    is $site->_human_date('2026-08-08'), '8 August 2026',    'leading zeroes dropped';
    is $site->_human_date('2025-12-31'), '31 December 2025', 'December is December';
    is $site->_human_date('2025-01-01'), '1 January 2025',   'January is January';

    # A bare $MONTH[$month - 1] turns each of these into December.
    is $site->_human_date('2025-00-01'), '2025-00-01', 'month 00 passed through';
    is $site->_human_date('2025-13-01'), '2025-13-01', 'month 13 passed through';
    is $site->_human_date('not a date'), 'not a date', 'junk passed through';
    is $site->_human_date(undef),        undef,        'undef passed through';
};

subtest 'the type label is the singular of the article type' => sub {
    my $article = $site->_latest_posts_html( [ post( type => 'article' ) ] );
    my $blog    = $site->_latest_posts_html( [ post( type => 'blog', directory => 'blog' ) ] );

    like $article, qr{<p class="meta">Article &middot;}, 'articles labelled Article';
    like $blog,    qr{<p class="meta">Blog &middot;},    'blog posts labelled Blog';
    like $blog,    qr{href="/blog/a-title"},             'blog links use the blog directory';
};

done_testing;
