#!/usr/bin/env perl

# root/include/links.tt is the site nav. Deployed /paad/ sub-sites are hand-run
# from bin/ scripts rather than generated by the build, so nothing else asserts
# they stay reachable from the nav.

use Test::Most;
use lib 'lib';
use Test2::Plugin::UTF8;
use Less::Boilerplate;
use Template;

my $tt = Template->new(
    {   INCLUDE_PATH => 'root',
        PLUGIN_BASE  => 'Template::Plugin',
        ABSOLUTE     => 0,
    }
) or die Template->error;

my $output = '';
$tt->process( 'include/links.tt', {}, \$output )
  or die $tt->error;

like $output, qr{<a href="/paad/">Learn PAAD</a>},
  'nav links to the PAAD course at /paad/';

# The desktop CSS hides the "Menu" summary, so the markup -- not CSS -- has to
# guarantee the list is open: Firefox <= 140 (current ESR) gives a closed
# <details>'s children no frames, and no author rule can reach inside. Drop the
# attribute and every such browser gets an empty nav band at desktop widths.
like $output, qr{<details class="nav-disclosure" open>},
  'nav disclosure ships open so the links show without ::details-content';
like $output, qr{nav\.open = e\.matches},
  'inline script collapses the nav again below the desktop breakpoint';

done_testing;
