#!/usr/bin/env perl

# root/include/links.tt is the site nav. Deployed /paad/ sub-sites are hand-run
# from bin/ scripts rather than generated by the build, so nothing else asserts
# they stay reachable from the nav.

use Test::Most;
use lib 'lib';
use Test2::Plugin::UTF8;
use Less::Boilerplate;
use Template;

my $tt = Template->new(
    {   INCLUDE_PATH => 'root',
        PLUGIN_BASE  => 'Template::Plugin',
        ABSOLUTE     => 0,
    }
) or die Template->error;

my $output = '';
$tt->process( 'include/links.tt', {}, \$output )
  or die $tt->error;

like $output, qr{<a href="/paad/">Learn PAAD</a>},
  'nav links to the PAAD course at /paad/';

done_testing;
